[tox]
min_version = 4
env_list =
    pre-commit,
    mypy-pkg,
    py3{10,11}-{tests,mypy}
    py3{10,11}-tests-{colorama,be,rich},
    docs,
    coverage-report


[testenv]
package = wheel
wheel_build_env = .pkg
extras =
    tests: tests=
commands =
    tests: pytest {posargs}=


[testenv:py3{10}-tests{,-colorama,-be,-rich}]
set_env =
    py310: COVERAGE_CORE=sysmon
deps =
    coverage[toml]
    py310: twisted
    colorama: colorama
    rich: rich
    be: better-exceptions
commands = coverage run -m pytest {posargs}


[testenv:coverage-report]
# Keep in-sync with .python-version-default
base_python = py310
deps = coverage[toml]
skip_install = true
parallel_show_output = true
# Keep in-sync with test env definition above.
depends = py3{10}-{tests,colorama,be,rich}
commands =
    coverage combine
    coverage report


[testenv:mypy-pkg]
extras = typing
commands = mypy modular_sdk
